"""Export the current best.pt to src/engine/weights.json for the web app.

Manual step — run it after training. The JSON is committed to git; it is
deliberately NOT regenerated by `npm run build`.

Run:  python training/scripts/export_weights.py
"""

from __future__ import annotations

import datetime
import json
import os
import sys

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
TRAINING_DIR = os.path.dirname(THIS_DIR)
sys.path.insert(0, TRAINING_DIR)

import torch  # noqa: E402

import config  # noqa: E402
from alphazero.network import PolicyValueNet  # noqa: E402
from games.foxlite import INPUT_SIZE, NUM_CARDS  # noqa: E402

REPO_ROOT = os.path.dirname(TRAINING_DIR)
CHECKPOINT = os.path.join(TRAINING_DIR, "checkpoints", "best.pt")
OUT_PATH = os.path.join(REPO_ROOT, "src", "engine", "weights.json")


def _layer(linear: torch.nn.Linear) -> dict:
    """Serialize a Linear layer: w is row-major [out][in], b is [out]."""
    return {
        "w": linear.weight.detach().tolist(),
        "b": linear.bias.detach().tolist(),
    }


def main() -> None:
    net = PolicyValueNet()
    net.load_state_dict(torch.load(CHECKPOINT, map_location="cpu"))
    net.eval()

    data = {
        "meta": {
            "inputSize": INPUT_SIZE,
            "actionSize": NUM_CARDS,
            "hiddenSize": config.HIDDEN_SIZE,
            "trunkLayers": config.TRUNK_LAYERS,
            "cPuct": config.C_PUCT,
            "numSimulations": config.PLAY_SIMULATIONS,
            "numDeterminizations": config.PLAY_DETERMINIZATIONS,
            "checkpoint": "checkpoints/best.pt",
            "exportedAt": datetime.date.today().isoformat(),
        },
        "trunk": [_layer(layer) for layer in net.trunk],
        "policyHead": _layer(net.policy_head),
        "valueHead": _layer(net.value_head),
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(data, f)

    shapes = [(len(l["w"]), len(l["w"][0])) for l in data["trunk"]]
    print(f"exported {CHECKPOINT}\n"
          f"      -> {OUT_PATH}\n"
          f"  trunk layers : {shapes}\n"
          f"  policy head  : ({len(data['policyHead']['w'])}, "
          f"{len(data['policyHead']['w'][0])})\n"
          f"  value head   : ({len(data['valueHead']['w'])}, "
          f"{len(data['valueHead']['w'][0])})")


if __name__ == "__main__":
    main()
